import NextHead from "next/head";

export default function Head(props) {
	return (
		<NextHead>
			<title>{props.title}</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</NextHead>
	);
}
